{
 "title": "user",
 "time": { "from": "now-8m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "GET /user RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{method=\"GET\",route=\"/user\",code=\"200\"}[1m])"
    }
   ]
  },
  {
   "title": "GET /user 200",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{method=\"GET\",route=\"/user\",code=\"200\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "GET /user 500",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{method=\"GET\",route=\"/user\",code=\"500\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "GET /user 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n    sum(rate(\n        http_request_duration_seconds_bucket{method=\"GET\"}[1m]\n    )) by (method,le)\n)"
    }
   ]
  },
  {
   "title": "POST /user RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{method=\"POST\",route=\"/user\",code=\"201\"}[1m])"
    }
   ]
  },
  {
   "title": "POST /user 200",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{method=\"POST\",route=\"/user\",code=\"201\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "POST /user 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n    sum(rate(\n        http_request_duration_seconds_bucket{method=\"POST\"}[$__interval]\n    )) by (method,le)\n)"
    }
   ]
  },
  {
   "title": "POST /user 500",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{method=\"POST\",route=\"/user\",code=\"500\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "consumer (msg/sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(consumer_messages_total{processor=\"cache\"}[$__interval])",
     "legendFormat": "{{processor}}"
    },
    {
     "expr": "sum by (processor) (rate(consumer_messages_total{processor=\"search\"}[$__interval]))",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "queue capacity (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "(consumer_queue_length{processor=\"cache\"}/consumer_queue_capacity{processor=\"cache\"})*100"
    },
    {
     "expr": "avg by (processor)((consumer_queue_length{processor=\"search\"}/consumer_queue_capacity{processor=\"search\"})*100)"
    }
   ]
  },
  {
   "title": "message lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "consumer_lag{processor=\"cache\"}"
    },
    {
     "expr": "sum(consumer_lag{processor=\"search\"})"
    }
   ]
  }
 ]
}