{
 "title": "Request duration",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(request_duration_seconds_count{method=\"GET\",route=\"/user\",code=\"200\"}[1m])"
    }
   ]
  },
  {
   "title": "GET /user 200",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_bucket{method=\"GET\",route=\"/user\",code=\"200\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "GET /user 500",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_bucket{method=\"GET\",route=\"/user\",code=\"500\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}