{
 "title": "user",
 "time": { "from": "now-8m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "GET /user RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum without (net_host_name,http_status_code) (rate(http_server_duration_milliseconds_count{http_method=\"GET\", http_route=\"/user\"}[1m]))"
    }
   ]
  },
  {
   "title": "GET /user 200",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_bucket{http_method=\"GET\",http_route=\"/user\",http_status_code=\"200\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "GET /user 5xx",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_bucket{http_method=\"GET\",http_route=\"/user\",http_status_code=~\"5.+\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "GET /user 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n    sum(rate(\n        http_server_duration_milliseconds_bucket{http_method=\"GET\"}[1m]\n    )) by (http_method,le)\n)"
    }
   ]
  },
  {
   "title": "POST /user RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum without (net_host_name) (rate(http_server_duration_milliseconds_count{http_method=\"POST\", http_route=\"/user\"}[1m]))"
    }
   ]
  },
  {
   "title": "POST /user 201",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_bucket{http_method=\"POST\",http_route=\"/user\",http_status_code=\"201\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "POST /user 5xx",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_bucket{http_method=\"POST\",http_route=\"/user\",http_status_code=~\"5.+\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "POST /user 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n    sum(rate(\n        http_server_duration_milliseconds_bucket{http_method=\"POST\"}[$__interval]\n    )) by (http_method,le)\n)"
    }
   ]
  },
  {
   "title": "consumer (msg/sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (destination) (rate(kafka_consumer_messages_total{destination=\"cache\"}[$__interval]))",
     "legendFormat": "{{processor}}"
    },
    {
     "expr": "sum by (destination) (rate(kafka_consumer_messages_total{destination=\"search\"}[$__interval]))",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "queue capacity (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "avg by (destination)((kafka_consumer_queue_length{destination=\"cache\"}/kafka_consumer_queue_capacity{destination=\"cache\"})*100)"
    },
    {
     "expr": "avg by (destination)((kafka_consumer_queue_length{destination=\"search\"}/kafka_consumer_queue_capacity{destination=\"search\"})*100)"
    }
   ]
  },
  {
   "title": "message lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(kafka_consumer_lag{destination=\"cache\"})"
    },
    {
     "expr": "sum(kafka_consumer_lag{destination=\"search\"})"
    }
   ]
  }
 ]
}